# -*- coding: utf-8 -*-
"""Endpoints orcamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XBkQRMK_YIdNXjbxRpmoo6qULsSt99o
"""

!pip install requests

import requests
from bs4 import BeautifulSoup

# Define os anos e meses para o loop
anos = list(range(2020, 2024))  # Ajuste os anos conforme necessário
meses = list(range(1, 13))  # Janeiro (1) a Dezembro (12)

# Função para gerar a URL com base no ano e mês
def generate_url(base_url, year, month):
    return base_url.format(year, str(month).zfill(2))

# Função para baixar os dados de um endpoint específico
def download_data(endpoint, year, month):
    url = generate_url(endpoint, year, month)
    response = requests.get(url)

    if response.status_code == 200:
        filename = f"data_{year}_{str(month).zfill(2)}.csv"
        with open(filename, 'wb') as file:
            file.write(response.content)
        print(f"Downloaded: {filename}")
    else:
        print(f"Failed to download data for {year}-{str(month).zfill(2)} from {url}")

# Lista de endpoints a serem percorridos
endpoints = [
    "https://www.portaltransparencia.gov.br/download-de-dados/auxilio-brasil/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/auxilio-emergencial/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/bolsa-familia-pagamentos/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/bolsa-familia-saques/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/novo-bolsa-familia/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/garantia-safra/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/seguro-defeso/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/peti/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/bpc/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/cpgf/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/cpcc/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/cpdc/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/favorecidos-pj/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/convenios/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/despesas/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/despesas-execucao/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/transferencias/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/despesas-favorecidos/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/emendas-parlamentares/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/imoveis-funcionais/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/licitacoes/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/compras/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/notas-fiscais/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/orcamento-despesa/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/receitas/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/renuncias/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/ceis/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/cepim/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/cnep/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/acordos-leniencia/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/servidores/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/ceaf/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/pep/{}{}",
    "https://www.portaltransparencia.gov.br/download-de-dados/viagens/{}{}"
]

# Percorre todos os anos e meses para cada endpoint
for endpoint in endpoints:
    for ano in anos:
        for mes in meses:
            download_data(endpoint, ano, mes)

